[server]
headless = true
enableCORS = false
enableXsrfProtection = true

[client]
showErrorDetails = false
toolbarMode = "minimal"

[theme]
primaryColor = "#38bdf8"
backgroundColor = "#050814"
secondaryBackgroundColor = "#0b1932"
textColor = "#e0f7ff"
font = "sans serif"
